### ISSUE TITLE
Multiple track support

### ISSUE THREAD

**Issue by mmathys** [hexahedria/biaxial-rnn-music-composition#13]
@hexahedria, can you predict what happens if you feed midi files which have multiple tracks? Is it supported, does it select the first track of the midi file?

If there is no support, I'm ready to take up development and add this feature...

**Comment by hexahedria** [comment]
Right now it squashes all tracks together. So if there are notes being played in multiple tracks, it effectively combines them all into a single stream of notes. This works well if you have a midi file with multiple instruments playing different parts, because it combines the parts together and feeds all of the notes to the network.

**Comment by mmathys** [comment]
Thanks a lot.
