### ISSUE TITLE
Question about BEAT input 

### ISSUE THREAD

**Issue by GreenHex6** [hexahedria/biaxial-rnn-music-composition#36]
Hello, I'm Trying to understand precisely how it all works and do my own version from ground up. 

However, I don't understand how exactly beat input works. It has fixed pattern. Can I observe that pattern in the note sheet ? 
How do we come up with this exact pattern for 4/4 ? 

Why the beat has 4 inputs ? ( rows)

It would be very helpful if someone could explain this to me in more details. I do a Bachelor thesis and I'm kind of stuck with this bit.

**Comment by danieldjohnson** [comment]
Hi Nikodem,

The beat input is an extra input that doesn't come from the note sheet. The pattern is synchronized with the measures in the piece, so that it restarts at the start of every measure in the note sheet.

The choice of pattern was somewhat arbitrary, but I based it on a binary sequence (if you read each column from bottom to top, it spells each number from 0 to 15 in binary). There are four rows because that's how many rows you need to uniquely identify a single 16th note in a 4/4 measure, and the majority of the music I was using was in 4/4 time.

Hope that helps.
